export const SIDE_BAR_TOGGLE = "SIDE_BAR_TOGGLE";
export const SELECT_PROJECT_CODE = "SELECT_PROJECT_CODE";
export const RECEVIE_GROUP = "RECEVIE_GROUP";
export const RECEVIE_SEARCH_KEY = "RECEVIE_SEARCH_KEY";
export const RECEVIE_MEMBER_IN_GROUP = "RECEVIE_MEMBER_IN_GROUP";
export const REMOVE_MEMBER_IN_GROUP = "REMOVE_MEMBER_IN_GROUP";
